### ISSUE TITLE
Overriding appium actions

### ISSUE THREAD

**Issue by ganjarpanji** [automationhacks/ama#3]
I need my test to log every step and actions during the test execution, is it possible if we `override` the appium existing action methods with our custom functions?
in case lest say appium has `click()` function to perfrom click on element, then i will create a function `click()` that also override the existing functionality and add one more line to print log.
original code :
```
func click() { 
  element.click
}
```

new overriden code :
```
func click() {
  element.click
  print("i clicked x element")
}
```

**Comment by automationhacks** [comment]
Yes. You could do that. Instead of `print` it could be a `logger` that would send these logs to your reporting solution.
