### ISSUE TITLE
Under your API Testing In Python - Test Automation University

### ISSUE THREAD

**Issue by Obumneke97** [automationhacks/ama#7]
Good day Sir,
I was following the Web UI Python Path on TAU and got to API Testing in Python. Please I need you to assist. You did not really state how to go about the setup for someone using a windows computer. If i am being correct you started by saying "if you are on Mac or Linux, you can use homebrew" and you pretty much kept doing things on homebrew and further went to Preferences on your Mac for other settings.
This got me lost as i do not even know how to get to homebrew or how to install that on my windows and/or any other steps required for that setup.
Please if you could assist with a step by step method as to go through setting up the virtual env for a user with Windows. 
Thank you

**Comment by automationhacks** [comment]
Hello @Obumneke97, I'm sorry for this experience. Hopefully, you figured this out by now.

We don't have homebrew on windows, you can either use chocolatey as an equivalent or follow tutorials for Python and pipenv on windows. 

[This](https://docs.python-guide.org/starting/install3/win/) is a good guide

I'm closing this, but please feel free to let me know in case you are still stuck.
